@startuml ClassDiagram
class Node {
    +List<Node> Neighbors
    +bool IsOccupied
    +Vector3 Position
    +void ConnectTo(Node other)
    +void DisconnectFrom(Node other)
}

class Pillar {
    +PillarSize Size
}

class Bridge{
    +void Initialize(Vector3 from, Vector3 to)
}

class MapManager {
    +static MapManager Instance
    +List<Node> Nodes
    +List<Pillar> Pillars
    +List<Bridge> Bridges
    +List<Node> Spawners
    +abstarct Pillar StartPillar
    +virtual List<Node> FindRoute(Node from, Node to)
    +void ConnectPillars(Pillar pillar1, Pillar pillar2)
    +abstract void GenerateMap()
}

class PoissonSampler {
    +static List<Vector2> GeneratePoissonPoints(int count, float radius, (float, float) xRange, (float, float) yRange, int maxAttempts, List<Vector2> existingPoints)
}

class Vector2Comparer {
    +bool Equals(Vector2 a, Vector2 b)
    +int GetHashCode(Vector2 v)
}

class TriangleNetWrapper {
    +static List<(Vector2, Vector2)> GenerateDelaunayEdges(List<Vector2> points)
    +static List<(Vector2, Vector2)> GenerateConstrainedDelaunayEdges(List<Vector2> points, List<(Vector2, Vector2)> constraints)
}

class GeometryUtils {
    +static List<Vector2> ComputeConvexHull(List<Vector2> points)
    +static List<(Vector2, Vector2)> GetHullEdges(List<Vector2> convexHull)
}

class RandomMapManager {
    +override Pillar StartPillar
    +override void GenerateMap()
}

class Unit {
    +Node CurrentNode
    +bool TryMoveTo(Node targetNode)
    +bool CanMoveTo(Node targetNode)
}

class Player {
    +int Life
    +void Initialize(Node startNode)
    +void TakeDamage(int damage)
}

class Enemy {
    +void Initialize(Node startNode, IPlayer player)
    +void Act()
}

class TurnSystem {
    +static TurnSystem Instance
    +TurnState CurrentTurn
    +int TurnCount
    +event Action<TurnState> OnTurnChanged
    +bool IsPlayerTurn()
    +bool IsEnemyTurn()
    +void EndPlayerTurn()
    +void EndEnemyTurn()
}

class UnitManager {
    +static UnitManager Instance
    +Player Player
    +List<Enemy> Enemies
    +void InitializePlayer()
    +void SpawnWave(int count)
    +void SpawnEnemyAtRandomSpawner()
    +void SpawnEnemy(Node node)
    +void RemoveDestroyedEnemies()
}

class UnitSystem {
    +static UnitSystem Instance
    +Initialize()
}

class GameManager {
    +static GameManager Instance
}

Node <|-- Pillar
Node <|-- Bridge
MapManager <|-- RandomMapManager
Unit <|-- Player
Unit <|-- Enemy
Node *-- MapManager
Vector2Comparer *-- TriangleNetWrapper
Vector2Comparer *-- GeometryUtils
Pillar *-- RandomMapManager
Bridge *-- RandomMapManager
PoissonSampler *-- RandomMapManager
TriangleNetWrapper *-- RandomMapManager
GeometryUtils *-- RandomMapManager
Node *-- Unit
Node *-- Player
Node *-- Enemy
Player *-- Enemy
TurnSystem *-- Player
MapManager *-- UnitManager
Player *-- UnitManager
Enemy *-- UnitManager
UnitManager *-- UnitSystem
TurnSystem *-- UnitSystem
MapManager *-- GameManager
UnitSystem *-- GameManager
@enduml

