@startuml ClassDiagram
class Node {
    +List<Node> Neighbors
    +bool IsOccupied
    +void ConnectTo(Node other)
    +void DisconnectFrom(Node other)
}

class Pillar {
    -PillarSize size
    +PillarSize Size
    +List<Pillar> AdjacentPillars
    +Bridge CreateBridgeTo(Pillar other)
}

class Bridge{

}

class MapManager {
    +static MapManager Instance
    -List<Node> Nodes
    +virtual List<Node> FindRoute(Node from, Node to)
    +abstract void GenerateMap()
}

class RandomMapManager {

}

Node <|-- Pillar
Node <|-- Bridge
MapManager <|-- RandomMapManager
Node *-- MapManager
Pillar *-- RandomMapManager
Bridge *-- RandomMapManager
@enduml

